     description="python-keycloak is a Python package providing access to the Keycloak API.",
     long_description=long_description,
     long_description_content_type="text/markdown",
    packages=["keycloak"],
     install_requires=reqs,
     tests_require=dev_reqs,
     extras_require={"docs": docs_reqs},