 # All configuration values have a default; values that are commented out
 # serve to show the default.
 
import sys, os
 
 # If extensions (or modules to document with autodoc) are in another directory,
 # add these directories to sys.path here. If the directory is relative to the
 
 # General information about the project.
 project = u"libnmap"
copyright = u"CC-BY 2013, Ronald Bister"
 
 # The version info for the project you're documenting, acts as replacement for
 # |version| and |release|, also used in various other places throughout the
 # built documents.
 #
 # The short X.Y version.
version = "0.2"
 # The full version, including alpha/beta/rc tags.
release = "0.2"
 
 # The language for content autogenerated by Sphinx. Refer to documentation
 # for a list of supported languages.
 # Grouping the document tree into LaTeX files. List of tuples
 # (source start file, target name, title, author, documentclass [howto/manual]).
 latex_documents = [
    ("index", "libnmap.tex", u"libnmap Documentation", u"Ronald Bister", "manual")
 ]
 
 # The name of an image file (relative to this directory) to place at the top of
 
 # One entry per manual page. List of tuples
 # (source start file, name, description, authors, manual section).
man_pages = [("index", "libnmap", u"libnmap Documentation", [u"Ronald Bister"], 1)]
 
 # If true, show URL addresses after external links.
 # man_show_urls = False